parameters:
#    ruian_twitter_bootstrap.example.class: Ruian\TwitterBootstrapBundle\Example

services:
#    ruian_twitter_bootstrap.example:
#        class: %ruian_twitter_bootstrap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
